reanahub/reana-ui

- README.rst
- docs/developerguide.rst
Basic developer guide in order to do a local deployment and test the UI
> docs: basic developers guide

- docs/developerguide.rst
- reana-ui/package.json
- run-tests.sh
[Prettier](https://prettier.io) has been chosen as the code styler package.
It is included in the "developpers guide" and in the `run-tests.sh`
> docs: introducing Prettier

- reana-ui/package.json
- reana-ui/src/App.js
- reana-ui/src/components/LoginForm.js
- reana-ui/src/components/WorkflowList.js
- reana-ui/src/config.js
- reana-ui/src/pages/Login.js
- reana-ui/src/pages/Workflows.js
**NOT** work in progress any more
> Login page

- reana-ui/package.json
Signed-off-by: Leticia Farias Wanderley <leticia.farias.wanderley@cern.ch>
> ui: update outdated dependencies

- reana-ui/src/pages/login/components/LoginForm.js
Signed-off-by: Leticia Farias Wanderley <leticia.farias.wanderley@cern.ch>
> ui: add cern sso login link

- Dockerfile
- nginx/reana-ui.conf
- reana-ui/src/components/Header.js
- reana-ui/src/config.js
- reana-ui/src/index.js
- reana-ui/src/pages/gitlabProjects/GitLabProjects.js
- reana-ui/src/pages/login/components/LoginForm.js
- reana-ui/src/pages/workflowDetails/components/WorkflowFiles.js
- reana-ui/src/pages/workflowDetails/components/WorkflowSpace.js
- reana-ui/src/pages/workflowDetails/components/workflowLogs.js
- reana-ui/src/pages/workflowsList/components/WorkflowsList.js
> ui create projects page

- reana-ui/src/pages/workflowDetails/components/WorkflowSpace.js
- reana-ui/src/pages/workflowsList/components/WorkflowsList.js
> workflow-list: remove cookie dependency to load

- reana-ui/src/pages/gitlabProjects/GitLabProjects.css
- reana-ui/src/pages/gitlabProjects/GitLabProjects.js
closes #38 
depends on https://github.com/reanahub/reana-server/pull/189
Current look:
> projects: use toggle to indicate integration

- reana-ui/package.json
- reana-ui/src/components/App.js
- reana-ui/src/components/CodeSnippet.js
- reana-ui/src/components/CodeSnippet.module.scss
- reana-ui/src/components/TopHeader.js
- reana-ui/src/pages/login/Login.js
- reana-ui/src/pages/profile/components/Token.js
- reana-ui/src/pages/workflowsList/components/NoWorkflows.js
- reana-ui/src/pages/workflowsList/components/NoWorkflows.module.scss
- reana-ui/src/pages/workflowsList/components/WorkflowsList.js
> ui: add no workflows page

- reana-ui/src/components/Title.js
- reana-ui/src/config.js
- reana-ui/src/pages/workflowList/components/WorkflowList.js
- reana-ui/src/pages/workflowList/components/WorkflowList.module.scss
- reana-ui/src/styles/palette.scss
* Reduces polling frequency
* Displays "refreshed at" in workflow list
* Updates docs links
> ui: minor fixes

- reana-ui/src/pages/workflowDetails/components/WorkflowLogs.js
> wf-details: display failed steps on load

- reana-ui/src/actions.js
- reana-ui/src/components/App.js
closes reanahub/reana-client#383
> user: print error message from server

- reana-ui/package.json
- reana-ui/src/pages/workflowDetails/components/WorkflowFiles.js
- reana-ui/src/util.js
> wf-files: add mime-type based whitelisting

- reana-ui/src/pages/workflowDetails/WorkflowDetails.js
> wf-details: fix non-existing workflow display

- reana-ui/src/pages/workflowList/components/NoWorkflows.js
Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>
> welcome: use `reana` Python virtual environment

- reana-ui/src/actions.js
- reana-ui/src/pages/workflowDetails/WorkflowDetails.js
- reana-ui/src/pages/workflowDetails/components/WorkflowSpecification.js
- reana-ui/src/reducers.js
- reana-ui/src/selectors.js
closes reanahub/reana-server#226
> wf-spec: display runtime params if exist

- reana-ui/package.json
* Build error https://github.com/facebook/create-react-app/issues/8680
fixed in https://github.com/facebook/create-react-app/issues/8661
released in
[react-scripts `3.4.1`](https://github.com/facebook/create-react-app/releases/tag/v3.4.1).
> build: fix build

- reana-ui/src/config.js
Addresses https://github.com/reanahub/reana/pull/289. 
Closes #90.
> config: use window.location to get API URL

- reana-ui/src/actions.js
- reana-ui/src/components/App.js
- reana-ui/src/components/Error.js
- reana-ui/src/components/Error.module.scss
- reana-ui/src/components/TopHeader.js
- reana-ui/src/pages/workflowList/components/Welcome.js
- reana-ui/src/reducers.js
- reana-ui/src/selectors.js
> global: show user email in profile popup

- reana-ui/src/pages/workflowList/components/Welcome.js
- reana-ui/src/pages/workflowList/components/Welcome.module.scss
- reana-ui/src/reducers.js
- reana-ui/src/selectors.js
> ui: display token request time

- Dockerfile
Decreases `craco build` time from ~250s to ~50s 🙏
> docker: bump to node 12

- reana-ui/src/components/Announcement.js
- reana-ui/src/components/Announcement.module.scss
- reana-ui/src/components/index.js
- reana-ui/src/pages/BasePage.js
- reana-ui/src/reducers.js
- reana-ui/src/selectors.js
> ui: add announcement component

- reana-ui/package.json
webpack-contrib/less-loader#366
Partially addresses #109
> package: unpin less-loader

- reana-ui/src/actions.js
- reana-ui/src/pages/workflowDetails/components/WorkflowFiles.js
- reana-ui/src/pages/workflowDetails/components/WorkflowFiles.module.scss
- reana-ui/src/pages/workflowList/WorkflowList.js
- reana-ui/src/pages/workflowList/WorkflowList.module.scss
- reana-ui/src/reducers.js
- reana-ui/src/selectors.js
closes reanahub/reana-server#180
> ui: pagination

- reana-ui/src/pages/workflowDetails/WorkflowDetails.js
- reana-ui/src/reducers.js
- reana-ui/src/selectors.js
> ui: fixed firefox issue in workflow details page

- reana-ui/src/components/Pagination.js
- reana-ui/src/components/index.js
- reana-ui/src/pages/workflowDetails/components/WorkflowFiles.js
- reana-ui/src/pages/workflowList/WorkflowList.js
> ui: improved the looks of pagination

- reana-ui/src/pages/signin/Signin.js
> ui: avoid setting state of unmounted component

- reana-ui/package.json
- reana-ui/src/actions.js
- reana-ui/src/pages/profile/components/GitLabProjects.js
- reana-ui/src/pages/workflowDetails/components/WorkflowFiles.js
- reana-ui/src/pages/workflowDetails/components/WorkflowLogs.js
- reana-ui/src/pages/workflowDetails/components/WorkflowSpecification.js
- reana-ui/src/pages/workflowList/WorkflowList.js
- reana-ui/src/pages/workflowList/WorkflowList.module.scss
- reana-ui/src/pages/workflowList/components/WorkflowFilters.js
- reana-ui/src/pages/workflowList/components/WorkflowFilters.module.scss
- reana-ui/src/pages/workflowList/components/WorkflowList.js
- reana-ui/src/pages/workflowList/components/WorkflowList.module.scss
- reana-ui/src/pages/workflowList/components/WorkflowSearch.js
- reana-ui/src/pages/workflowList/components/WorkflowSorting.js
- reana-ui/src/pages/workflowList/components/WorkflowStatusFilter.js
- reana-ui/src/reducers.js
- reana-ui/src/selectors.js
- reana-ui/src/util.js
> ui: implemented filtering in workflow list page

- reana-ui/src/actions.js
- reana-ui/src/components/Notification.js
- reana-ui/src/pages/workflowDetails/WorkflowDetails.js
- reana-ui/src/pages/workflowDetails/components/WorkflowInfo.js
- reana-ui/src/pages/workflowList/components/WorkflowActionsPopup.js
- reana-ui/src/pages/workflowList/components/WorkflowActionsPopup.module.scss
- reana-ui/src/pages/workflowList/components/WorkflowDeleteModal.js
- reana-ui/src/pages/workflowList/components/WorkflowList.js
- reana-ui/src/pages/workflowList/components/WorkflowList.module.scss
- reana-ui/src/pages/workflowList/components/index.js
- reana-ui/src/props.js
- reana-ui/src/reducers.js
- reana-ui/src/selectors.js
- reana-ui/src/util.js
> ui: introduce workflow deletion

- reana-ui/package.json
- reana-ui/src/actions.js
- reana-ui/src/components/Title.js
- reana-ui/src/pages/profile/Profile.js
- reana-ui/src/pages/profile/components/Quota.js
- reana-ui/src/pages/profile/components/Quota.module.scss
- reana-ui/src/reducers.js
- reana-ui/src/selectors.js
> ui: display user quota on profile page 

- reana-ui/src/pages/workflowList/WorkflowList.js
- reana-ui/src/reducers.js
> global: fix fypo

- reana-ui/src/components/WorkflowActionsPopup.js
- reana-ui/src/components/WorkflowDeleteModal.js
- reana-ui/src/pages/profile/components/Quota.js
- reana-ui/src/pages/workflowDetails/components/WorkflowFiles.js
- reana-ui/src/pages/workflowList/components/WorkflowList.js
* Closes reanahub/reana-server#296.
> global: display sizes in human readable across UI

- CHANGES.rst
- reana-ui/jsconfig.json
- reana-ui/src/pages/profile/Profile.js
> profile: hide quotas and gitlab sections while token is not granted

- .github/workflows/ci.yml
- Dockerfile
- run-tests.sh
addresses https://github.com/reanahub/reana/issues/450
> ci: add hadolint linter

- reana-ui/src/components/WorkflowActionsPopup.js
- reana-ui/src/pages/workflowList/components/WorkflowList.js
- reana-ui/src/props.js
> ui: fix highlighting disk usage when wf is deleted

- reana-ui/src/pages/signin/Signin.js
Only display it when user email confirmation is enabled.
> auth: hide SSO sign up notification

- reana-ui/src/pages/workflowDetails/components/WorkflowInfo.js
- reana-ui/src/util.js
closes https://github.com/reanahub/reana-workflow-controller/issues/363
> ui: added new pending status support

- reana-ui/src/actions.js
- reana-ui/src/components/App.js
- reana-ui/src/components/Footer.js
- reana-ui/src/components/PieChart.js
- reana-ui/src/components/Title.module.scss
- reana-ui/src/components/index.js
- reana-ui/src/pages/profile/Profile.module.scss
- reana-ui/src/pages/profile/components/Quota.js
- reana-ui/src/pages/status/Status.js
- reana-ui/src/pages/status/Status.module.scss
- reana-ui/src/util.js
> ui: add cluster health status page

- reana-ui/package.json
Closes https://github.com/reanahub/reana/issues/512
> release: 0.8.0-alpha.2

- reana-ui/src/pages/workflowList/components/WorkflowList.js
- reana-ui/src/pages/workflowList/components/WorkflowList.module.scss
> wf-list: display disk size in new line

- reana-ui/src/actions.js
- reana-ui/src/client.js
- reana-ui/src/components/PieChart.js
- reana-ui/src/components/WorkflowActionsPopup.js
- reana-ui/src/components/WorkflowDeleteModal.js
- reana-ui/src/pages/profile/Profile.js
- reana-ui/src/pages/profile/components/GitLabProjects.js
- reana-ui/src/pages/signin/Signin.js
- reana-ui/src/pages/status/Status.js
- reana-ui/src/pages/workflowDetails/components/WorkflowFiles.js
- reana-ui/src/pages/workflowDetails/components/WorkflowInfo.js
- reana-ui/src/pages/workflowList/components/WorkflowList.js
- reana-ui/src/pages/workflowList/components/WorkflowList.module.scss
- reana-ui/src/reducers.js
- reana-ui/src/util.js
closes reanahub/reana#562
closes #198
> profile: hide quota section when disabled

- CHANGES.rst
- reana-ui/src/components/PieChart.js
- reana-ui/src/pages/status/Status.js
- reana-ui/src/pages/status/Status.module.scss
closes https://github.com/reanahub/reana-ui/issues/206
> ui: improve colors in cluster health status page

- CHANGES.rst
- reana-ui/package.json
- reana-ui/yarn.lock
- package: bump `node-sass` to version 7
- package: update yarn.lock
> package: bump `node-sass` to version 7

- CHANGES.rst
- reana-ui/package.json
- reana-ui/src/client.js
- reana-ui/src/components/App.js
- reana-ui/src/config.js
- reana-ui/src/hooks.js
- reana-ui/src/pages/launchOnReana/LaunchOnReana.js
- reana-ui/src/pages/launchOnReana/LaunchOnReana.module.scss
- reana-ui/src/pages/launchOnReana/__tests__/LaunchOnReana.test.js
- reana-ui/src/setupTests.js
- reana-ui/yarn.lock
closes #221
closes #223
**To test:**
- Boot up l[ocal REANA-UI](https://github.com/reanahub/reana-ui#readme)
- Access `http://localhost:3000/launch?url=https://zenodo.org/foo/bar/reana.yaml&name=myanalysis&parameters={%22events%22%3A%222000%22}&foo=bar` or similar.
- Edit `client.js`'s `launchWorkflow` function test multiple scenarios based on `Promises`
```js
const mockData = {
data: {
workflow_id: "cdcf48b1-c2f3-4693-8230-b066e088c6ac",
workflow_name: "mytest.1",
message: "The workflow has been successfully submitted.",
},
};
// Delayed Success `Promise` (Spinner)
function delay(t, v) {
return new Promise(function (resolve) {
setTimeout(resolve.bind(null, v), t);
});
}
return delay(5000, mockData);
// Regular Success `Promise`
return Promise.resolve(mockData);
// Rejection `Promise` …
```
> ui: `LaunchOnReana` page

- CHANGES.rst
- reana-ui/src/client.js
- reana-ui/src/pages/signin/Signin.js
> auth: redirect to requested page after sso login

- CHANGES.rst
- reana-ui/src/pages/launchOnReana/__tests__/LaunchOnReana.test.js
- reana-ui/src/pages/workflowDetails/components/LauncherLabel.js
- reana-ui/src/pages/workflowDetails/components/WorkflowInfo.js
- reana-ui/src/pages/workflowDetails/components/WorkflowInfo.module.scss
- reana-ui/src/pages/workflowDetails/components/__tests__/LauncherLabel.test.js
- reana-ui/src/pages/workflowDetails/components/index.js
- reana-ui/src/pages/workflowList/components/WorkflowList.module.scss
- reana-ui/src/util.js
> WorkflowInfo: display workflow launcher label

- reana-ui/src/pages/error/NotFound.js
- reana-ui/src/pages/workflowDetails/components/WorkflowInfo.js
> wf-details: fix misplaced refresh button

- reana-ui/src/config.js
Closes reanahub/reana-server#452
> LaunchOnReana: add `spec` parameter

- reana-ui/src/components/WorkflowActionsPopup.module.scss
- reana-ui/src/pages/workflowDetails/components/WorkflowInfo.js
- reana-ui/src/pages/workflowDetails/components/WorkflowInfo.module.scss
- reana-ui/src/pages/workflowList/WorkflowList.js
- reana-ui/src/pages/workflowList/WorkflowList.module.scss
- reana-ui/src/pages/workflowList/components/WorkflowList.module.scss
closes https://github.com/reanahub/reana-ui/issues/244
closes https://github.com/reanahub/reana-ui/issues/245
closes #249
> global: minor UI fixes

- reana-ui/src/actions.js
- reana-ui/src/config.js
- reana-ui/src/pages/launchOnReana/LaunchOnReana.js
- reana-ui/src/pages/launchOnReana/Welcome.js
- reana-ui/src/pages/launchOnReana/__tests__/LaunchOnReana.test.js
- reana-ui/src/pages/profile/Profile.js
- reana-ui/src/reducers.js
- profile: fetch user quotas when navigating to profile page
- launcher: rename `spec` to `specification`
> profile: fetch user quotas when navigating to profile page

- reana-ui/src/pages/workflowDetails/components/WorkflowLogs.js
- reana-ui/src/pages/workflowDetails/components/WorkflowLogs.module.scss
- reana-ui/yarn.lock
Fixes https://github.com/reanahub/reana-ui/pull/252 among other vulnerabilities.
closes https://github.com/reanahub/reana-ui/issues/247
> wf-details: fix long step name wrapping issue

- CHANGES.rst
- reana-ui/package.json
- reana-ui/src/client.js
- reana-ui/src/components/App.js
- reana-ui/src/pages/signin/OAuthSignin.js
closes https://github.com/reanahub/reana-server/issues/480
> auth: migrate to the new SSO

- AUTHORS.rst
- CHANGES.rst
- reana-ui/src/pages/workflowDetails/WorkflowDetails.js
> wf-details: refresh after workflow deletion

- CHANGES.rst
- reana-ui/src/config.js
- reana-ui/src/pages/workflowDetails/WorkflowDetails.js
- reana-ui/src/pages/workflowDetails/components/WorkflowInfo.js
- reana-ui/src/pages/workflowDetails/components/WorkflowLogs.js
- reana-ui/src/selectors.js
- reana-ui/src/util.js
> wf-details: show the logs of the workflow engine

- nginx/reana-ui.conf
- reana-ui/src/actions.js
- reana-ui/src/components/App.js
- reana-ui/src/components/WorkflowActionsPopup.js
- reana-ui/src/pages/workflowDetails/WorkflowDetails.js
> router: do not change URL when showing 404 error page

- CHANGES.rst
- reana-ui/src/pages/workflowList/components/WorkflowSorting.js
closes https://github.com/reanahub/reana-ui/issues/270
> ui: add new most quota used sorting options to workflow list page

- reana-ui/src/components/WorkflowActionsPopup.js
> ui: permit closing Jupyter notebook when workflow is deleted

- CHANGES.rst
- reana-ui/src/pages/workflowDetails/components/WorkflowFiles.js
- reana-ui/src/pages/workflowDetails/components/WorkflowRetentionRules.js
- reana-ui/src/pages/workflowDetails/components/WorkflowRetentionRules.module.scss
- reana-ui/src/pages/workflowDetails/components/index.js
- reana-ui/src/util.js
How to test:
1. Execute some workflows
2. Open the details page of one of the workflows
3. Check that retention rules are correctly displayed in the `Workspace` tab
> wf-details: show retention rules in Workspace tab

- CHANGES.rst
- reana-ui/src/pages/workflowDetails/components/WorkflowLogs.js
- reana-ui/src/pages/workflowDetails/components/WorkflowLogs.module.scss
- reana-ui/src/util.js
> wf-details: show duration of jobs

- reana-ui/src/pages/workflowDetails/components/WorkflowRetentionRules.js
- reana-ui/src/util.js
> wf-details: improve approximate time before retention rule

- reana-ui/src/pages/launchOnReana/LaunchOnReana.js
Closes reanahub/reana-server#516
> launcher: redirect to welcome page if user doesn't have a token

- reana-ui/src/pages/workflowDetails/components/WorkflowRetentionRules.js
- reana-ui/src/pages/workflowDetails/components/WorkflowRetentionRules.module.scss
- reana-ui/src/styles/palette.scss
> wf-details: improve retention rules table

- reana-ui/src/pages/workflowDetails/components/WorkflowRetentionRules.js
- reana-ui/src/util.js
- reana-ui/src/util.test.js
Closes reanahub/reana-server#526
> wf-details: show `pending` status for retention rules

- CHANGES.rst
- reana-ui/package.json
- reana-ui/src/components/Announcement.js
- reana-ui/src/config.js
- reana-ui/yarn.lock
> ui: allow markup in announcement

- reana-ui/src/components/WorkflowDeleteModal.js
closes https://github.com/reanahub/reana-client/issues/649
> ui: suggest deleting also an open session in a deletion modal

- CHANGES.rst
- reana-ui/src/pages/workflowDetails/components/WorkflowFiles.js
- reana-ui/src/pages/workflowDetails/components/WorkflowFiles.module.scss
> wf-details: add preview for PDF files

- reana-ui/src/components/Footer.js
- reana-ui/src/pages/privacyNotice/PrivacyNotice.js
- reana-ui/src/pages/status/Status.js
Change titles to conform to sentence case and to remove unnecessary
icons.
Closes #315
> ui: harmonise titles

- reana-ui/src/util.js
Change the way in which the displayed workflow duration is calculated
depending on the status of the workflow: if the workflow is finished or
deleted, take as "finished" moment the value `run_finished_at`, but if
the workflow is stopped, consider `run_stopped_at` as the ending moment
relative to which the duration is calculated.
Closes #337
> util: change wf duration calculation depending on status

- reana-ui/src/pages/workflowDetails/components/filePreview/FilePreview.js
- reana-ui/src/reducers.js
- reana-ui/src/util.js
- reana-ui/src/util.test.js
> preview: get maximum file size from config

- reana-ui/package.json
- reana-ui/yarn.lock
- installation: bump all dependencies
- release: 0.9.1-alpha.4
> release: 0.9.1-alpha.4

- CHANGES.rst
- reana-ui/src/pages/launchOnReana/Welcome.js
- reana-ui/src/pages/launchOnReana/Welcome.module.scss
- reana-ui/src/reducers.js
> launch: fetch list of demo repos from config map

- CHANGES.rst
- reana-ui/package.json
- reana-ui/yarn.lock
- package: update yarn.lock
- release: 0.9.1
> release: 0.9.1

- CHANGES.rst
- reana-ui/package.json
- reana-ui/src/components/Notification.js
- reana-ui/src/pages/workflowDetails/components/WorkflowInfo.js
- reana-ui/src/pages/workflowDetails/components/WorkflowRetentionRules.js
- reana-ui/src/pages/workflowList/components/WorkflowList.js
- reana-ui/yarn.lock
> release: 0.9.2

- reana-ui/src/components/App.js
> fix(router): show 404 page for invalid URLs (#382)

- reana-ui/src/pages/badgeCreator/LauncherBadgeCreator.js
> fix(launcher-badge): remove dollar sign in generated markdown

- Dockerfile
> build(docker): fix FromAsCasing warning (#411)

- Dockerfile
> build(docker): fix FromAsCasing warning
