reanahub/reana-ui

- .travis.yml
- README.rst
- run-tests.sh
* Adds initial Travis CI configuration. (closes #2)
* Removes coveralls from README documentation.
* Note: switches off the JS prettier test for now, because the `master` branch
does not contain any JS code yet. It can be plugged in when the first
prototype is merged.
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
> travis: initial configuration

- reana-ui/package.json
- reana-ui/public/index.html
- reana-ui/public/manifest.json
- reana-ui/src/App.js
- reana-ui/src/components/Header.js
- reana-ui/src/components/WorkflowActions.js
- reana-ui/src/components/WorkflowList.js
- reana-ui/src/components/WorkflowProgress.js
- reana-ui/src/images/logo-reana.svg
- reana-ui/src/index.js
- reana-ui/src/pages/Workflows.js
- run-tests.sh
First steps of the workflow-list implementation
Connect #10
> Workflow list

- docs/developerguide.rst
* REANA-Cluster is being deprecated so we are removing all references
to it (closes reanahub/reana#238).
* Updates developer instructions to comply with latest Helm procedures.
> docs: remove reana-cluster references

- reana-ui/src/components/CodeSnippet.module.scss
- reana-ui/src/pages/workflowDetails/components/WorkflowLogs.module.scss
- reana-ui/src/pages/workflowDetails/components/WorkflowSpecification.js
- reana-ui/src/pages/workflowDetails/components/WorkflowSpecification.module.scss
> wf-details: fix specification overflow

- reana-ui/src/components/CodeSnippet.js
- reana-ui/src/components/CodeSnippet.module.scss
- reana-ui/src/pages/profile/components/Token.js
- reana-ui/src/pages/workflowList/components/Welcome.js
- reana-ui/src/pages/workflowList/components/Welcome.module.scss
Now reana token is hidden by default.
Introduces new `reveal` prop in `<CodeSnippet />` to reveal parts marked as `revealable`.
> ui: make token in code snippet revealable

- reana-ui/src/actions.js
- reana-ui/src/components/Notification.js
- reana-ui/src/components/Notification.module.scss
- reana-ui/src/components/index.js
- reana-ui/src/pages/BasePage.js
- reana-ui/src/pages/workflowDetails/WorkflowDetails.js
- reana-ui/src/pages/workflowList/components/Welcome.js
- reana-ui/src/reducers.js
- reana-ui/src/selectors.js
> ui: added generic error notification component

- reana-ui/src/actions.js
- reana-ui/src/pages/signin/Signin.js
- reana-ui/src/pages/workflowList/WorkflowList.js
- reana-ui/src/reducers.js
- reana-ui/src/selectors.js
- Avoids infinite loop of `fetchWorkflows` requests if config endpoint misbehaves (pollingSecs).
- Avoids displaying welcome page when an exception happens on server.
- Gets rid of all `fetch()` calls, replacing them with `axios` calls.
partially addresses #46
closes #155
> actions: improve error handling

- reana-ui/src/components/App.js
- reana-ui/src/pages/signin/Signin.js
- reana-ui/src/pages/signin/Signup.js
- reana-ui/src/reducers.js
- reana-ui/src/selectors.js
addresses https://github.com/reanahub/reana/issues/469
> ui: control signup form visibility with configs

- reana-ui/src/actions.js
- reana-ui/src/components/App.js
- reana-ui/src/components/Notification.js
- reana-ui/src/pages/signin/Confirm.js
- reana-ui/src/pages/signin/Signin.js
- reana-ui/src/pages/signin/components/SignContainer.js
- reana-ui/src/pages/workflowDetails/WorkflowDetails.js
- reana-ui/src/reducers.js
- reana-ui/src/selectors.js
closes reanahub/reana#472
TODO:
- if token invalid, display error notification from server and redirect to home.
- if token valid, trigger success notification and redirect to home.
**Steps to test:**
1. Enable `notifications` in [Helm `values.yaml`](https://github.com/reanahub/reana/blob/2ff64da2563fe5c5a968b56ea90e983439deb22a/helm/reana/values.yaml#L83):
```yaml
notifications:
enabled: true
email_config:
sender: admin@reana.io
```
2. Sign up a new local user (you should see a success notification)
3. Check [MailDev](http://localhost:32580), you should have received a confirmation email.
4. Copy the link in the email and replace the hostname and HTTPS->HTTP suitably
5. Paste it in your favorite browser, you should be redirected to the home page and a notification must show up, error or …
> auth: add email confirmation page

- README.rst
This PR fixes the [`README.rst`](https://github.com/reanahub/reana-ui/blob/master/README.rst) CI shield and URL, both still pointing to _Travis_.
> docs: fix readme CI URL

- CHANGES.rst
- Dockerfile
- README.rst
- reana-ui/package.json
- reana-ui/src/actions.js
- reana-ui/src/client.js
- reana-ui/src/components/Search.js
- reana-ui/src/components/Search.module.scss
- reana-ui/src/components/index.js
- reana-ui/src/pages/workflowDetails/components/WorkflowFiles.js
- reana-ui/src/pages/workflowList/WorkflowList.js
- reana-ui/src/util.js
- reana-ui/src/util.test.js
- reana-ui/yarn.lock
closes #211
closes #204
https://user-images.githubusercontent.com/8863238/149172123-d18f801d-8f11-4858-acd8-c8b019efdf14.mov
**Test:**
- To be tested thoroughly rebuilding the REANA-UI docker image as it involves a change in the Node.js version.
> workspace: add file search

- reana-ui/src/pages/signin/Signin.js
- reana-ui/src/pages/workflowDetails/components/WorkflowFiles.js
- reana-ui/src/pages/workflowDetails/components/WorkflowFiles.module.scss
closes https://github.com/reanahub/reana-ui/issues/179
closes https://github.com/reanahub/reana-ui/issues/230
In order to test https://github.com/reanahub/reana-ui/issues/230:
use some network throttling (GPRS worked for me) and observe that the message is no longer present in Workspace tab.
Try to delete some workspace to see that it's displayed when needed.
In order to test https://github.com/reanahub/reana-ui/issues/179:
modify `cernSSO`, `localUsers`, `hideSignup` in `config reducer` [here](https://github.com/reanahub/reana-ui/blob/master/reana-ui/src/reducers.js#L129) 
Here is how the main use cases looks like after this PR:
- Production settings (`cernSSO: true, localUsers: false, hideSignup: true`)
- `cernSSO: false, localUsers: true, hideSignup: false`
- `cernSSO: false, …
> ui: improve sso login text

- CHANGES.rst
- reana-ui/src/actions.js
- reana-ui/src/client.js
- reana-ui/src/pages/workflowList/WorkflowList.js
closes https://github.com/reanahub/reana-ui/issues/229
The problem was that when user refreshed detailed workflow page, [fetchWorkflow(id) action](https://github.com/reanahub/reana-ui/blob/master/reana-ui/src/actions.js#L271) was triggered which fetched all of the user workflows. For users who created lots of the workflows this operation was not very optimal.. This PR fixes this issue by fetching a specific workflow in this case.
To test go to detailed workflow page, do a hard refresh and inspect that only a specific workflow was fetched instead all of them.
> client: improve fetching workflow by id

- reana-ui/src/pages/launchOnReana/LaunchOnReana.js
Closes #239 
How to test: Try to reproduce the issue
Expected result: The error notification is not shown after successfully launching a workflow
> LaunchOnReana: clear notifications after workflow launch

- reana-ui/src/pages/signin/Signin.js
The SSO sign-in message now reads:
The link to `reana-qa.cern.ch` is not user friendly, because it leads to the same page... The user does not learn anything new by following it.
This commit improves the UX by simply removing the link.
> ui: simplify SSO sign-in message

- reana-ui/src/actions.js
This PR fixes an issue that caused some notifications not to be correctly shown to the user, for example when deleting workflows or opening Jupyter notebooks.
How to test:
Delete a workflow from the REANA homepage and check that notifications are correctly displayed at the top of the page.
> actions: add missing default parameter to `triggerNotification`

- CHANGES.rst
- reana-ui/src/pages/workflowDetails/components/WorkflowFiles.js
Closes #274 
This PR also changes the workflow-details page to show file sizes in a human-readable format.
How to test:
- Execute one of the example workflows
- Go to the `Workspace` tab and sort the files by size
Expected result: the files are correctly sorted by increasing/decreasing size
> wf-details: fix ordering of files by size

- CHANGES.rst
- reana-ui/src/components/Notification.js
- reana-ui/src/components/NotificationBell.js
- reana-ui/src/components/TopHeader.js
- reana-ui/src/config.js
- reana-ui/src/pages/profile/components/Quota.js
- reana-ui/src/pages/profile/components/Quota.module.scss
- reana-ui/src/util.js
closes https://github.com/reanahub/reana-ui/issues/160
- Adds notification icon to the header to inform users when critical levels of quota usage is reached
- Adds same messages to Profile page under `Your quota` section
- Renames `HDD` to `Disk` in Profile page quotas section to be compatible with CLI
- Removes `help` button from the header
To test:
- Change `termination_update_policy` to `disk,cpu` in [values.yaml](https://github.com/reanahub/reana/blob/master/helm/reana/values.yaml) and redeploy
- Run some workflows
- Set some quota limits:
```
kubectl exec -i -t deployment/reana-server -- flask reana-admin quota-set -r disk -e john.doe@example.org -l 500000
kubectl exec -i -t deployment/reana-server -- flask reana-admin quota-set -r cpu -e john.doe@example.org -l 500000
```
- Verify …
> ui: add notification icon to inform when critical levels of quota usage is reached

- CHANGES.rst
- reana-ui/src/actions.js
- reana-ui/src/components/WorkflowActionsPopup.js
- reana-ui/src/components/WorkflowDeleteModal.js
- reana-ui/src/pages/workflowDetails/components/WorkflowInfo.js
- reana-ui/src/pages/workflowList/components/WorkflowList.js
Closes #280 
How to test:
1. Run some demo workflows
2. Delete one of them
3. Open the details page of the deleted workflow
Expected result: The workspace is deleted together with the workflow and the workflow duration is shown in both the workflow list and in the details page
> ui: always delete workspace when deleting workflow

- reana-ui/src/pages/workflowDetails/components/WorkflowRetentionRules.js
Improves retention message verbiage for new, not yet run workflows.
Status before:
Status after:
> wf-details: improve retention message

- CHANGES.rst
- reana-ui/src/components/WorkflowActionsPopup.js
- reana-ui/src/reducers.js
Changes the interactive session notification by adding a message stating that the session will be closed after a specified number of days.
closes https://github.com/reanahub/reana-workflow-controller/issues/498
> ui: enrich interactive session notification with termination time

- CHANGES.rst
- reana-ui/src/actions.js
- reana-ui/src/client.js
- reana-ui/src/components/WorkflowActionsPopup.js
- reana-ui/src/components/WorkflowStopModal.js
- reana-ui/src/components/index.js
- reana-ui/src/pages/workflowDetails/WorkflowDetails.js
- reana-ui/src/pages/workflowList/components/WorkflowList.js
- reana-ui/src/reducers.js
- reana-ui/src/selectors.js
- reana-ui/src/util.js
> ui: add item to actions popup to allow stopping workflow

- nginx/reana-ui.conf
- reana-ui/package.json
Compress JS/CSS files with gzip after `yarn build` and configure nginx
to serve the pre-compressed files.
Closes #328
> nginx: serve gzip-compressed static files

- Dockerfile
- run-tests.sh
Adds fully qualified canonical locations of container images, making the container technology setup podman-friendly.
Closes reanahub/reana#729.
> docker: podman-friendly image locations

- reana-ui/src/actions.js
- reana-ui/src/components/Notification.js
- reana-ui/src/pages/launchOnReana/LaunchOnReana.js
- reana-ui/src/reducers.js
Closes https://github.com/reanahub/reana-client/issues/660.
To test launching a workflow with an unexpected property declared inside the REANA specification file, this link can be used: `http://localhost:3000/launch?url=https://github.com/giuseppe-steduto/reana-demo-root6-roofit/tree/reana-yaml-allow-unexpected-props&specification=reana-cwl.yaml`
> launch: display success/warning message after submission

- CHANGES.rst
- reana-ui/src/pages/workflowDetails/components/WorkflowProgress.js
Changes the workflow progress bar to always show 100% for workflows that
are in status `finished`, so that even when some steps are restored from
cache, the progress bar stays consistent with the status of the
workflow.
Closes reanahub/reana-workflow-engine-snakemake#62.
How to test cached workflows:
1. Run the roofit snakemake demo with `reana-client run -w r-snake -f ./reana-snakemake.yaml`
2. Restart the workflow in the same workspace, so that snakemake restores it completely from the cache: `reana-client restart r-snake`. Verify that the progress bar is at 100% with 0/0 steps (as shown locally by Snakemake)
3. Edit the `code/fitdata.C` file (e.g. change a comment) and upload it to the same workspace: `reana-client upload -w r-snake code/fitdata.C`
4. Restart the workflow in the same …
> wf-details: always fill progress bar for finished workflows

- CHANGES.rst
- reana-ui/src/pages/workflowDetails/components/WorkflowLogs.js
Changes the JobLogs component so that instead of constantly updating the
logs to show the last "failed" or "running" step, the step is changed
only on page load, or when the list of logs change from being empty to
having at least one entry.
Closes #351.
> wf-details: do not change chosen log tab automatically

- .github/workflows/ci.yml
- CHANGES.rst
- Dockerfile
Use node 18 instead of node 16, as the former is the default version on
Fedora/Ubuntu and the latter has reached EOL.
Closes #347
> global: upgrade to node 18

- CHANGES.rst
- reana-ui/package.json
- reana-ui/src/actions.js
- reana-ui/src/client.js
- reana-ui/src/components/WorkflowDeleteModal.js
- reana-ui/yarn.lock
- package: upgrade jsroot to 7.5.0
- client: make parameters optional in getWorkflows
- ui: add option to delete all workflow runs
Closes https://github.com/reanahub/reana-ui/issues/349
> ui: add option to delete all workflow runs

- CHANGES.rst
- reana-ui/src/client.js
- reana-ui/src/components/App.js
- reana-ui/src/pages/badgeCreator/LauncherBadgeCreator.js
- reana-ui/src/pages/badgeCreator/LauncherBadgeCreator.module.scss
- reana-ui/src/pages/launchOnReana/LaunchOnReana.js
- reana-ui/src/pages/launchOnReana/LaunchOnReana.module.scss
- reana-ui/src/pages/launchOnReana/Welcome.js
- reana-ui/src/pages/launchOnReana/__tests__/LaunchOnReana.test.js
- **launch: display parameters in table**
Change the launch page so that the optional parameters are displayed
in a table, where each row correspond to a parameter, and the value of
each of them is displayed in its JSON-serialized version.
This allows to correctly show even complex parameters like objects and
lists.
- **launch: add launcher URL and badge creator page**
- **client: fix no-anonymous-default-export linting warning**
Closes #324.
> add "launch on REANA" badge and launcher URL creator

- .release-please-config.json
Switch to the `simple` release strategy as the `node` one does not
handle correctly having package.json in a subdirectory.
> ci(release-please): switch to `simple` release strategy (#383)

- reana-ui/src/util.js
- reana-ui/src/util.test.js
- run-tests.sh
- fix(utils): update failed workflows duration using finished time
Fix the way in which the duration of failed workflows is calculated, to
use the time at which the run was finished rather than the current time.
Closes #386
- ci(shellcheck): exclude node_modules from the analyzed paths
> fix(utils): update failed workflows duration using finished time

- reana-ui/src/client.js
- reana-ui/src/components/Search.js
- reana-ui/src/pages/profile/components/GitLabProjects.js
- reana-ui/src/pages/profile/components/GitLabProjects.module.scss
- feat(gitlab): add filtering for GitLab project lists (#403)
- feat(gitlab): add pagination for GitLab project lists (#403)
BREAKING CHANGE: The REST API endpoint `gitlab_projects` now includes
pagination details.
Closes reanahub/reana-server#518
> feat(gitlab): add filtering and pagination (#403)

- reana-ui/src/actions.js
- reana-ui/src/client.js
- reana-ui/src/components/InteractiveSessionModal.js
- reana-ui/src/components/WorkflowActionsPopup.js
- reana-ui/src/components/index.js
- reana-ui/src/pages/workflowDetails/WorkflowDetails.js
- reana-ui/src/pages/workflowList/components/WorkflowList.js
- reana-ui/src/reducers.js
- reana-ui/src/selectors.js
Closes reanahub/reana-workflow-controller#569
> feat(sessions): add modal for choosing session environment (#405)

- reana-ui/src/client.js
- reana-ui/src/components/DaskIcon.js
- reana-ui/src/components/DaskIcon.module.scss
- reana-ui/src/components/WorkflowBadges.js
- reana-ui/src/components/index.js
This PR adds `Dask dashboard badge` which redirects users to Dask dashboard page upon click.
>  feat(workflow-badges): add Dask dashboard icon
